#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice1.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Invoice1")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDocType(DocType instance);
    partial void UpdateDocType(DocType instance);
    partial void DeleteDocType(DocType instance);
    partial void InsertStore(Store instance);
    partial void UpdateStore(Store instance);
    partial void DeleteStore(Store instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void UpdateInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void DeleteInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void Insertitem(item instance);
    partial void Updateitem(item instance);
    partial void Deleteitem(item instance);
    partial void InsertItemStore(ItemStore instance);
    partial void UpdateItemStore(ItemStore instance);
    partial void DeleteItemStore(ItemStore instance);
    partial void InsertInvoiceMaster(InvoiceMaster instance);
    partial void UpdateInvoiceMaster(InvoiceMaster instance);
    partial void DeleteInvoiceMaster(InvoiceMaster instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Invoice1.Properties.Settings.Default.Invoice1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DocType> DocTypes
		{
			get
			{
				return this.GetTable<DocType>();
			}
		}
		
		public System.Data.Linq.Table<Store> Stores
		{
			get
			{
				return this.GetTable<Store>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceMasterDetail> InvoiceMasterDetails
		{
			get
			{
				return this.GetTable<InvoiceMasterDetail>();
			}
		}
		
		public System.Data.Linq.Table<item> items
		{
			get
			{
				return this.GetTable<item>();
			}
		}
		
		public System.Data.Linq.Table<ItemStore> ItemStores
		{
			get
			{
				return this.GetTable<ItemStore>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceMaster> InvoiceMasters
		{
			get
			{
				return this.GetTable<InvoiceMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocType")]
	public partial class DocType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DocTypeId;
		
		private string _DocTypeDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocTypeIdChanging(int value);
    partial void OnDocTypeIdChanged();
    partial void OnDocTypeDescChanging(string value);
    partial void OnDocTypeDescChanged();
    #endregion
		
		public DocType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DocTypeId
		{
			get
			{
				return this._DocTypeId;
			}
			set
			{
				if ((this._DocTypeId != value))
				{
					this.OnDocTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DocTypeId = value;
					this.SendPropertyChanged("DocTypeId");
					this.OnDocTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeDesc", DbType="NVarChar(MAX)")]
		public string DocTypeDesc
		{
			get
			{
				return this._DocTypeDesc;
			}
			set
			{
				if ((this._DocTypeDesc != value))
				{
					this.OnDocTypeDescChanging(value);
					this.SendPropertyChanging();
					this._DocTypeDesc = value;
					this.SendPropertyChanged("DocTypeDesc");
					this.OnDocTypeDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Store")]
	public partial class Store : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StoreId;
		
		private string _StoreDesc;
		
		private System.Nullable<bool> _StoreIsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStoreIdChanging(int value);
    partial void OnStoreIdChanged();
    partial void OnStoreDescChanging(string value);
    partial void OnStoreDescChanged();
    partial void OnStoreIsActiveChanging(System.Nullable<bool> value);
    partial void OnStoreIsActiveChanged();
    #endregion
		
		public Store()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreDesc", DbType="NVarChar(MAX)")]
		public string StoreDesc
		{
			get
			{
				return this._StoreDesc;
			}
			set
			{
				if ((this._StoreDesc != value))
				{
					this.OnStoreDescChanging(value);
					this.SendPropertyChanging();
					this._StoreDesc = value;
					this.SendPropertyChanged("StoreDesc");
					this.OnStoreDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreIsActive", DbType="Bit")]
		public System.Nullable<bool> StoreIsActive
		{
			get
			{
				return this._StoreIsActive;
			}
			set
			{
				if ((this._StoreIsActive != value))
				{
					this.OnStoreIsActiveChanging(value);
					this.SendPropertyChanging();
					this._StoreIsActive = value;
					this.SendPropertyChanged("StoreIsActive");
					this.OnStoreIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeId;
		
		private string _EmployeeName;
		
		private System.Nullable<System.DateTime> _EmployeeBirthDate;
		
		private System.Nullable<System.DateTime> _EmployeeHierDate;
		
		private System.Nullable<decimal> _EmployeeSalary;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnEmployeeBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmployeeBirthDateChanged();
    partial void OnEmployeeHierDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmployeeHierDateChanged();
    partial void OnEmployeeSalaryChanging(System.Nullable<decimal> value);
    partial void OnEmployeeSalaryChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(MAX)")]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EmployeeBirthDate
		{
			get
			{
				return this._EmployeeBirthDate;
			}
			set
			{
				if ((this._EmployeeBirthDate != value))
				{
					this.OnEmployeeBirthDateChanging(value);
					this.SendPropertyChanging();
					this._EmployeeBirthDate = value;
					this.SendPropertyChanged("EmployeeBirthDate");
					this.OnEmployeeBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeHierDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EmployeeHierDate
		{
			get
			{
				return this._EmployeeHierDate;
			}
			set
			{
				if ((this._EmployeeHierDate != value))
				{
					this.OnEmployeeHierDateChanging(value);
					this.SendPropertyChanging();
					this._EmployeeHierDate = value;
					this.SendPropertyChanged("EmployeeHierDate");
					this.OnEmployeeHierDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeSalary", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> EmployeeSalary
		{
			get
			{
				return this._EmployeeSalary;
			}
			set
			{
				if ((this._EmployeeSalary != value))
				{
					this.OnEmployeeSalaryChanging(value);
					this.SendPropertyChanging();
					this._EmployeeSalary = value;
					this.SendPropertyChanged("EmployeeSalary");
					this.OnEmployeeSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceMasterDetail")]
	public partial class InvoiceMasterDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InvoiceDetailId;
		
		private System.Nullable<int> _InvoiceId;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<decimal> _itemprice;
		
		private System.Nullable<decimal> _Quantity;
		
		private System.Nullable<int> _ItemId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceDetailIdChanging(int value);
    partial void OnInvoiceDetailIdChanged();
    partial void OnInvoiceIdChanging(System.Nullable<int> value);
    partial void OnInvoiceIdChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnitempriceChanging(System.Nullable<decimal> value);
    partial void OnitempriceChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnItemIdChanging(System.Nullable<int> value);
    partial void OnItemIdChanged();
    #endregion
		
		public InvoiceMasterDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InvoiceDetailId
		{
			get
			{
				return this._InvoiceDetailId;
			}
			set
			{
				if ((this._InvoiceDetailId != value))
				{
					this.OnInvoiceDetailIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDetailId = value;
					this.SendPropertyChanged("InvoiceDetailId");
					this.OnInvoiceDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId", DbType="Int")]
		public System.Nullable<int> InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceId = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemprice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> itemprice
		{
			get
			{
				return this._itemprice;
			}
			set
			{
				if ((this._itemprice != value))
				{
					this.OnitempriceChanging(value);
					this.SendPropertyChanging();
					this._itemprice = value;
					this.SendPropertyChanged("itemprice");
					this.OnitempriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int")]
		public System.Nullable<int> ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.items")]
	public partial class item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemId;
		
		private string _itemdesc;
		
		private System.Nullable<decimal> _itemsllprice;
		
		private System.Nullable<decimal> _itembuypirice;
		
		private System.Nullable<bool> _itemactive;
		
		private string _Barcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemIdChanging(int value);
    partial void OnItemIdChanged();
    partial void OnitemdescChanging(string value);
    partial void OnitemdescChanged();
    partial void OnitemsllpriceChanging(System.Nullable<decimal> value);
    partial void OnitemsllpriceChanged();
    partial void OnitembuypiriceChanging(System.Nullable<decimal> value);
    partial void OnitembuypiriceChanged();
    partial void OnitemactiveChanging(System.Nullable<bool> value);
    partial void OnitemactiveChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    #endregion
		
		public item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemdesc", DbType="NVarChar(MAX)")]
		public string itemdesc
		{
			get
			{
				return this._itemdesc;
			}
			set
			{
				if ((this._itemdesc != value))
				{
					this.OnitemdescChanging(value);
					this.SendPropertyChanging();
					this._itemdesc = value;
					this.SendPropertyChanged("itemdesc");
					this.OnitemdescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemsllprice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> itemsllprice
		{
			get
			{
				return this._itemsllprice;
			}
			set
			{
				if ((this._itemsllprice != value))
				{
					this.OnitemsllpriceChanging(value);
					this.SendPropertyChanging();
					this._itemsllprice = value;
					this.SendPropertyChanged("itemsllprice");
					this.OnitemsllpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itembuypirice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> itembuypirice
		{
			get
			{
				return this._itembuypirice;
			}
			set
			{
				if ((this._itembuypirice != value))
				{
					this.OnitembuypiriceChanging(value);
					this.SendPropertyChanging();
					this._itembuypirice = value;
					this.SendPropertyChanged("itembuypirice");
					this.OnitembuypiriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemactive", DbType="Bit")]
		public System.Nullable<bool> itemactive
		{
			get
			{
				return this._itemactive;
			}
			set
			{
				if ((this._itemactive != value))
				{
					this.OnitemactiveChanging(value);
					this.SendPropertyChanging();
					this._itemactive = value;
					this.SendPropertyChanged("itemactive");
					this.OnitemactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(MAX)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemStore")]
	public partial class ItemStore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemsStoreId;
		
		private System.Nullable<int> _ItemsId;
		
		private System.Nullable<decimal> _ItemQuantityOnHand;
		
		private System.Nullable<decimal> _ItemSellPrice;
		
		private System.Nullable<decimal> _ItemBuyPrice;
		
		private System.Nullable<int> _StoreId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemsStoreIdChanging(int value);
    partial void OnItemsStoreIdChanged();
    partial void OnItemsIdChanging(System.Nullable<int> value);
    partial void OnItemsIdChanged();
    partial void OnItemQuantityOnHandChanging(System.Nullable<decimal> value);
    partial void OnItemQuantityOnHandChanged();
    partial void OnItemSellPriceChanging(System.Nullable<decimal> value);
    partial void OnItemSellPriceChanged();
    partial void OnItemBuyPriceChanging(System.Nullable<decimal> value);
    partial void OnItemBuyPriceChanged();
    partial void OnStoreIdChanging(System.Nullable<int> value);
    partial void OnStoreIdChanged();
    #endregion
		
		public ItemStore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemsStoreId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ItemsStoreId
		{
			get
			{
				return this._ItemsStoreId;
			}
			set
			{
				if ((this._ItemsStoreId != value))
				{
					this.OnItemsStoreIdChanging(value);
					this.SendPropertyChanging();
					this._ItemsStoreId = value;
					this.SendPropertyChanged("ItemsStoreId");
					this.OnItemsStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemsId", DbType="Int")]
		public System.Nullable<int> ItemsId
		{
			get
			{
				return this._ItemsId;
			}
			set
			{
				if ((this._ItemsId != value))
				{
					this.OnItemsIdChanging(value);
					this.SendPropertyChanging();
					this._ItemsId = value;
					this.SendPropertyChanged("ItemsId");
					this.OnItemsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemQuantityOnHand", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ItemQuantityOnHand
		{
			get
			{
				return this._ItemQuantityOnHand;
			}
			set
			{
				if ((this._ItemQuantityOnHand != value))
				{
					this.OnItemQuantityOnHandChanging(value);
					this.SendPropertyChanging();
					this._ItemQuantityOnHand = value;
					this.SendPropertyChanged("ItemQuantityOnHand");
					this.OnItemQuantityOnHandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemSellPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ItemSellPrice
		{
			get
			{
				return this._ItemSellPrice;
			}
			set
			{
				if ((this._ItemSellPrice != value))
				{
					this.OnItemSellPriceChanging(value);
					this.SendPropertyChanging();
					this._ItemSellPrice = value;
					this.SendPropertyChanged("ItemSellPrice");
					this.OnItemSellPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemBuyPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ItemBuyPrice
		{
			get
			{
				return this._ItemBuyPrice;
			}
			set
			{
				if ((this._ItemBuyPrice != value))
				{
					this.OnItemBuyPriceChanging(value);
					this.SendPropertyChanging();
					this._ItemBuyPrice = value;
					this.SendPropertyChanged("ItemBuyPrice");
					this.OnItemBuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", DbType="Int")]
		public System.Nullable<int> StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceMaster")]
	public partial class InvoiceMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InvoiceId;
		
		private System.Nullable<decimal> _InvoiceDate;
		
		private System.Nullable<int> _StoreId;
		
		private System.Nullable<decimal> _InvoiceNetValue;
		
		private System.Nullable<decimal> _InvoiceNetValueAfterDiscount;
		
		private System.Nullable<decimal> _InvoiceDiscount;
		
		private System.Nullable<decimal> _SubmittedValue;
		
		private System.Nullable<int> _tregaryId;
		
		private System.Nullable<int> _EmployeeId;
		
		private System.Nullable<decimal> _MainDiscount;
		
		private System.Nullable<int> _DocTypeId;
		
		private System.Nullable<decimal> _LastFinalTotalDiscount;
		
		private System.Nullable<decimal> _FinalInvoiceWinValue;
		
		private System.Nullable<decimal> _InvoiceWinValue;
		
		private System.Nullable<decimal> _InvoiceNetValue2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceIdChanging(int value);
    partial void OnInvoiceIdChanged();
    partial void OnInvoiceDateChanging(System.Nullable<decimal> value);
    partial void OnInvoiceDateChanged();
    partial void OnStoreIdChanging(System.Nullable<int> value);
    partial void OnStoreIdChanged();
    partial void OnInvoiceNetValueChanging(System.Nullable<decimal> value);
    partial void OnInvoiceNetValueChanged();
    partial void OnInvoiceNetValueAfterDiscountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceNetValueAfterDiscountChanged();
    partial void OnInvoiceDiscountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceDiscountChanged();
    partial void OnSubmittedValueChanging(System.Nullable<decimal> value);
    partial void OnSubmittedValueChanged();
    partial void OntregaryIdChanging(System.Nullable<int> value);
    partial void OntregaryIdChanged();
    partial void OnEmployeeIdChanging(System.Nullable<int> value);
    partial void OnEmployeeIdChanged();
    partial void OnMainDiscountChanging(System.Nullable<decimal> value);
    partial void OnMainDiscountChanged();
    partial void OnDocTypeIdChanging(System.Nullable<int> value);
    partial void OnDocTypeIdChanged();
    partial void OnLastFinalTotalDiscountChanging(System.Nullable<decimal> value);
    partial void OnLastFinalTotalDiscountChanged();
    partial void OnFinalInvoiceWinValueChanging(System.Nullable<decimal> value);
    partial void OnFinalInvoiceWinValueChanged();
    partial void OnInvoiceWinValueChanging(System.Nullable<decimal> value);
    partial void OnInvoiceWinValueChanged();
    partial void OnInvoiceNetValue2Changing(System.Nullable<decimal> value);
    partial void OnInvoiceNetValue2Changed();
    #endregion
		
		public InvoiceMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceId = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", DbType="Int")]
		public System.Nullable<int> StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValue
		{
			get
			{
				return this._InvoiceNetValue;
			}
			set
			{
				if ((this._InvoiceNetValue != value))
				{
					this.OnInvoiceNetValueChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNetValue = value;
					this.SendPropertyChanged("InvoiceNetValue");
					this.OnInvoiceNetValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValueAfterDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValueAfterDiscount
		{
			get
			{
				return this._InvoiceNetValueAfterDiscount;
			}
			set
			{
				if ((this._InvoiceNetValueAfterDiscount != value))
				{
					this.OnInvoiceNetValueAfterDiscountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNetValueAfterDiscount = value;
					this.SendPropertyChanged("InvoiceNetValueAfterDiscount");
					this.OnInvoiceNetValueAfterDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceDiscount
		{
			get
			{
				return this._InvoiceDiscount;
			}
			set
			{
				if ((this._InvoiceDiscount != value))
				{
					this.OnInvoiceDiscountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDiscount = value;
					this.SendPropertyChanged("InvoiceDiscount");
					this.OnInvoiceDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SubmittedValue
		{
			get
			{
				return this._SubmittedValue;
			}
			set
			{
				if ((this._SubmittedValue != value))
				{
					this.OnSubmittedValueChanging(value);
					this.SendPropertyChanging();
					this._SubmittedValue = value;
					this.SendPropertyChanged("SubmittedValue");
					this.OnSubmittedValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tregaryId", DbType="Int")]
		public System.Nullable<int> tregaryId
		{
			get
			{
				return this._tregaryId;
			}
			set
			{
				if ((this._tregaryId != value))
				{
					this.OntregaryIdChanging(value);
					this.SendPropertyChanging();
					this._tregaryId = value;
					this.SendPropertyChanged("tregaryId");
					this.OntregaryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int")]
		public System.Nullable<int> EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MainDiscount
		{
			get
			{
				return this._MainDiscount;
			}
			set
			{
				if ((this._MainDiscount != value))
				{
					this.OnMainDiscountChanging(value);
					this.SendPropertyChanging();
					this._MainDiscount = value;
					this.SendPropertyChanged("MainDiscount");
					this.OnMainDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeId", DbType="Int")]
		public System.Nullable<int> DocTypeId
		{
			get
			{
				return this._DocTypeId;
			}
			set
			{
				if ((this._DocTypeId != value))
				{
					this.OnDocTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DocTypeId = value;
					this.SendPropertyChanged("DocTypeId");
					this.OnDocTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastFinalTotalDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LastFinalTotalDiscount
		{
			get
			{
				return this._LastFinalTotalDiscount;
			}
			set
			{
				if ((this._LastFinalTotalDiscount != value))
				{
					this.OnLastFinalTotalDiscountChanging(value);
					this.SendPropertyChanging();
					this._LastFinalTotalDiscount = value;
					this.SendPropertyChanged("LastFinalTotalDiscount");
					this.OnLastFinalTotalDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInvoiceWinValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FinalInvoiceWinValue
		{
			get
			{
				return this._FinalInvoiceWinValue;
			}
			set
			{
				if ((this._FinalInvoiceWinValue != value))
				{
					this.OnFinalInvoiceWinValueChanging(value);
					this.SendPropertyChanging();
					this._FinalInvoiceWinValue = value;
					this.SendPropertyChanged("FinalInvoiceWinValue");
					this.OnFinalInvoiceWinValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceWinValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceWinValue
		{
			get
			{
				return this._InvoiceWinValue;
			}
			set
			{
				if ((this._InvoiceWinValue != value))
				{
					this.OnInvoiceWinValueChanging(value);
					this.SendPropertyChanging();
					this._InvoiceWinValue = value;
					this.SendPropertyChanged("InvoiceWinValue");
					this.OnInvoiceWinValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValue2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValue2
		{
			get
			{
				return this._InvoiceNetValue2;
			}
			set
			{
				if ((this._InvoiceNetValue2 != value))
				{
					this.OnInvoiceNetValue2Changing(value);
					this.SendPropertyChanging();
					this._InvoiceNetValue2 = value;
					this.SendPropertyChanged("InvoiceNetValue2");
					this.OnInvoiceNetValue2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
